.TH SCALP 1
.SH NAME
scalp \- a Simple CALendar Program that actually only notifies you on certain events.
(a.k.a. todolist)
.SH SYNOPSIS
.SY scalp
.OP FILENAME
.YS
.SY scalp
add
.OP FILENAME
.YS
.SY scalp
del
.OP FILENAME
.YS
.SY scalp
help
.YS
.SY scalp
list
.OP FILENAME
.YS
.SY scalp
prune
.OP FILENAME
.YS
.SY scalp
update
.YS
.SH DESCRIPTION
.B scalp
is a simple calendar program that actually only notifies you on certain events.
Some people will not call this a calendar program, but a reminder / agenda /
todo-list program.
.PP
All the other calendar programs are too complicated, both in source code and in usage.
That's why scalp came in to being.
.PP
Beware that scalp is still in development.
.SH SUBCOMMANDS
.PP
Running scalp without any subcommands will start the daemon.
The program will notify the user with a message specified in the file once the specified
time arrives. The default filename is \fIfoo\fP.
.TP
.B add
will prompt the user to enter a time and a message. The message must not be longer than 512 characters long, and the time format is described in \fIdate\fP(1).
.TP
.B del
will prompt the user to give a number, which corresponds to the entry that the user wants to delete.
.TP
.B help
will show a help message.
.TP
.B list
will list all entries in a given file.
.TP
.B prune
will remove all entries older than now.
.TP
.B update
will update all running instances of scalp. This means that all instances of scalp running in daemon mode will reload their source file and then continue.
.SH USAGE EXAMPLES
.TP
It is recommended to start the scalp daemon on startup. For example, put this line in your \fI.bashrc\fP:
.EX
nohup scalp ~/.cache/calendar.scalp &
.EE
.TP
Here is an example of adding a new entry:
.EX
scalp add ~/.cache/calendar.scalp
Time: next Friday 6pm
Message: Homegroup at home!
.EE
.TP
Here is another one, for another file:
.EX
$ scalp add foo
Time: 2023-07-03
Message: Marc's birthday!
.EE
.TP
This shows the deletion of the entry of the homegroup entry (date may vary):
.EX
$ scalp del ~/.cache/calendar.scalp
1	Sat Sep 17 11:00:00 2022	Dad's birthday
2	Tue Sep 20 14:00:00 2022	Somebody's gonna roll me.
3	Wed Sep 21 07:21:21 2022	Country Road, take me home!
4	Fri Sep 23 18:00:00 2022	Homegroup at home!
Which event do you want to delete? 4
.EE
.TP
Here is an example of scalp list:
.EX
$ scalp list ~/.cache/calendar.scalp
Sat Sep 17 11:00:00 2022	Dad's birthday
Tue Sep 20 14:00:00 2022	Somebody's gonna roll me.
Wed Sep 21 07:21:21 2022	Country Road, take me home!
.EE
.TP
To remove old outdated entries, type this:
.EX
$ scalp prune foo
.EE
.TP
To update all instances of scalp (which is only necessary if you edit any files manually), do this:
.EX
$ scalp update
.EE
.SH FILE FORMAT
Each line contains a number, representing the number of seconds since Unix Epoch
(1st Jan 1970 12am UTC), a separating character (usually a tab, never a digit or a newline)
and a string of maximally 512 characters, representing the message to be displayed.
.PP
For example, the following line is a valid entry for scalp:
.EX
1660035600	Something happens!!
.EE
.PP
The file must end on a newline.
.SH FURTHER READING
More information can be found on 
.UR https://github.com/nmke-de/scalp
.UE .
